# @file 99-hardening.conf
# @brief Параметры тюнинга ядра Linux для повышения безопасности (Hardening)
# @author [Твоё ФИО] (your.email@university.com)
# @date 2026-05-30
# @version 1.0.0
# @license MIT
#
# @details
#   1. Отключение пересылки пакетов (мы не роутер)
#   2. Защита от SYN-флуда (cookies)
#   3. Игнорирование ICMP-редиректов (защита от подмены маршрутов)
#   4. Запись в лог подозрительных пакетов (martians)

# Включаем защиту от SYN-флуд атак
net.ipv4.tcp_syncookies = 1

# Отключаем IP forwarding (мы не шлюз)
net.ipv4.ip_forward = 0

# Отключаем прием и отправку ICMP Redirects (защита от ARP-spoofing)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0

# Включаем логирование "марсианских" (невозможных) пакетов
net.ipv4.conf.all.log_martians = 1

# Отключаем source routing (защита от подмены источника)
net.ipv4.conf.all.accept_source_route = 0
